# Generated by Django 3.0.3 on 2020-09-21 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BbsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
