# Generated by Django 3.0.3 on 2020-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BbsApp', '0002_bbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='viewcnt',
            field=models.IntegerField(default=0),
        ),
    ]
