# Generated by Django 3.0.3 on 2020-09-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BbsApp', '0003_bbs_viewcnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
