# Generated by Django 3.0.3 on 2020-09-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='regdate',
            field=models.DateTimeField(verbose_name='date pulished'),
        ),
    ]
