# Generated by Django 3.0.3 on 2020-09-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PollsApp', '0002_auto_20200918_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_text',
        ),
    ]
